/* Design-only, synthetic state. No API, storage, credentials or external requests. */
const params=new URLSearchParams(location.search);
const P=window.DM_PAGES.find(x=>x.id===params.get('page'))||window.DM_PAGES.find(x=>x.id==='buyer-documents');
let seq=0;
const icon=n=>window.DM_ICONS[n+'24Regular']||window.DM_ICONS.Info24Regular;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const link=(id,text,cls='')=>`<a class="${cls}" href="preview.html?page=${id}">${text}</a>`;
const btn=(text,action='notice',cls='',attrs='')=>`<button type="button" class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const badge=(text,tone='')=>`<span class="badge ${tone}">${text}</span>`;
const help=(label,text)=>{const id='help-'+(++seq);return `<span class="help-wrap"><button type="button" class="help" aria-label="Помощь: ${esc(label)}" aria-expanded="false" aria-describedby="${id}">?</button><span class="helptext" role="tooltip" id="${id}">${text}</span></span>`};
const field=(label,value='',hint='',type='text',extra='')=>{const id='field-'+(++seq);return `<div class="field"><label for="${id}">${label}${help(label,hint||'Уточняет данные этого действия. В прототипе значение не отправляется на сервер.')}</label>${type==='textarea'?`<textarea id="${id}" aria-label="${esc(label)}" ${extra}>${esc(value)}</textarea>`:`<input id="${id}" aria-label="${esc(label)}" type="${type}" value="${esc(value)}" ${extra}>`}</div>`};
const select=(label,options,hint='Выбор применяется только к текущей рабочей области.')=>{const id='field-'+(++seq);return `<div class="field"><label for="${id}">${label}${help(label,hint)}</label><select id="${id}" aria-label="${esc(label)}">${options.map(v=>`<option>${v}</option>`).join('')}</select></div>`};
const check=(label,checked=false,type='checkbox')=>{const id='choice-'+(++seq);return `<div class="checkline"><input id="${id}" type="${type}" ${checked?'checked':''}><label for="${id}">${label} ${help(label,'Выбирает это условие. Изменения применяются только после явного подтверждения, если оно предусмотрено формой.')}</label></div>`};
const banner=(title,text='',tone='')=>`<div class="banner ${tone}">${icon(tone==='bad'?'ErrorCircle':tone==='warn'?'Warning':tone==='good'?'CheckmarkCircle':'Info')}<div><strong>${title}</strong>${text?`<p>${text}</p>`:''}</div></div>`;
const panel=(title,body)=>`<section class="panel">${title?`<h2>${title}</h2>`:''}${body}</section>`;
const dl=rows=>`<dl class="dl">${rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('')}</dl>`;
const table=(heads,rows,cls='responsive')=>`<div class="table-wrap" tabindex="0" aria-label="Таблица: ${esc(heads.join(', '))}"><table class="table ${cls}"><thead><tr>${heads.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td data-label="${esc(heads[i]||'')}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const tabs=items=>`<div class="tabs" role="tablist" aria-label="Разделы страницы">${items.map((x,i)=>`<button type="button" role="tab" aria-selected="${i===0}" data-tab="${esc(x)}">${x}</button>`).join('')}</div>`;
const toolbar=(search='Номер, название или контрагент',filters=['Все статусы','За 30 дней'])=>`<div class="toolbar">${field('Поиск','',search,'search',`placeholder="${search}" data-filter`)}${filters.map((f,i)=>f.includes('типы')?select('Тип документа',[f,'Счёт','Квитанция','Накладная','Договор']):f.includes('склады')?select('Склад',[f,'Алматы']):f.includes('категории')?select('Категория',[f,'Терапия','Эндодонтия']):select(i?'Период / контекст':'Статус',[f,i?'Уточнить интервал':'Требует внимания'])).join('')}${btn(icon('Filter')+' Применить','filter')}${btn('Сбросить','reset','quiet')}</div>`;
const pager=n=>`<div class="pagination"><small>Показано ${n} из ${n} · синтетические записи</small><div class="pager">${btn('Назад','notice','small','disabled')}${btn('1','notice','primary small','aria-current="page"')}${btn('Далее','notice','small','disabled')}</div></div>`;
const money=n=>`<span class="money">${new Intl.NumberFormat('ru-RU').format(n)} ₸</span>`;
const doc=(name,meta)=>`<div class="item"><span class="doc-icon">${icon('Document')}</span><div><strong>${name}</strong><small>${meta}</small></div></div>`;
const qty=(n=1)=>`<div class="qty"><button type="button" data-action="minus" aria-label="Уменьшить количество">−</button><input type="number" value="${n}" min="0" aria-label="Количество упаковок"><button type="button" data-action="plus" aria-label="Увеличить количество">+</button></div>`;
const steps=(labels,current=1)=>`<ol class="steps">${labels.map((x,i)=>`<li class="${i<current?'done':i===current?'current':''}"><b>${i<current?'✓':i+1}</b>${x}</li>`).join('')}</ol>`;
const file=(name='Счёт-INV-0264.pdf',state='245 КБ · тестовый PDF')=>`<div class="file-row">${icon('Document')}<div><strong>${name}</strong><small>${state}</small></div>${btn(icon('MoreHorizontal'),'document-menu','icon','aria-label="Действия с файлом"')}</div>`;
const upload=()=>`<div class="upload">${icon('ArrowUpload')}<h3>Выберите файл документа</h3><p class="muted">PDF, JPG или PNG · допустимый размер определяется API</p>${field('Файл','','Документ будет связан с выбранной организацией и заказом. В прототипе файл никуда не отправляется.','file')}</div>`;
const timeline=()=>`<ol class="timeline"><li>Поставщик подтвердил 3 позиции<small>14 сентября, 11:20 · Демо-поставщик 01</small></li><li>Счёт сформирован<small>14 сентября, 11:21 · INV-0264</small></li><li>Заказ создан<small>14 сентября, 10:40 · Демо-клиника 01</small></li></ol>`;
const party=()=>P.role==='supplier'?'Демо-клиника 01':'Демо-поставщик 01';
const products=[['Композит универсальный A2','4 г',18900,24],['Эндодонтические файлы','6 шт.',7450,18],['Перчатки нитриловые M','100 шт.',3250,60]];
const itemRows=()=>products.map(([name,pack,price],i)=>[`${name}<small>Упаковка · ${pack}</small>`,money(price),(i<2?'2':'1')+' уп.',money(price*(i<2?2:1))]);
const rowsOrders=()=>[
[link(P.role==='supplier'?'supplier-order-detail':'buyer-order-detail','DM-0264'),party()+'<small>14 сентября · 10:40</small>',badge('Подтверждён','good'),badge('Не оплачено','warn'),money(55950),link(P.role==='supplier'?'supplier-order-detail':'buyer-order-detail','Открыть '+icon('ArrowRight'))],
['DM-0263',party()+'<small>13 сентября · 16:10</small>',badge('Получен','good'),badge('Подтверждена','good'),money(37800),btn('История','notice','small')],
['DM-0262','Демо-поставщик 02<small>12 сентября · 09:15</small>',badge('Ожидает подтверждения','warn'),badge('Не оплачено'),money(14900),btn('Открыть','notice','small')],
['DM-0261','Демо-поставщик 03<small>11 сентября · 14:00</small>',badge('Отменён'),badge('Не требуется'),money(3250),btn('Причина','reason','small')]
].filter((row,i)=>P.role!=='supplier'||i<2);
function documents(){const detail=P.role==='supplier'?'supplier-document-detail':'buyer-document-detail';return `<div class="subsummary"><span><strong>4</strong> документа</span><span>Связаны с заказами вашей организации</span></div>${toolbar('Номер, название или контрагент',['Все типы','Все даты'])}${table(['Документ','Контрагент','Заказ','Дата','Сумма','Статус',''],[
[doc(link(detail,'Счёт № INV-0264'),'PDF · 245 КБ'),party(),link('buyer-order-detail','DM-0264'),'14.09.2026',money(55950),badge('Сформирован','good'),btn(icon('MoreHorizontal'),'document-menu','icon','aria-label="Действия со счётом"')],
[doc('Накладная № НК-0264','PDF · 180 КБ'),party(),'DM-0264','14.09.2026',money(55950),badge('Черновик'),btn(icon('MoreHorizontal'),'document-menu','icon','aria-label="Действия с накладной"')],
[doc('Договор № РД-001','PDF · 320 КБ'),party(),'—','01.09.2026','—',badge('Тестовый документ'),btn(icon('MoreHorizontal'),'document-menu','icon','aria-label="Действия с договором"')],
[doc('Квитанция № КВ-0264','PDF · 210 КБ'),party(),'DM-0264','14.09.2026',money(55950),badge('На проверке','warn'),btn(icon('MoreHorizontal'),'document-menu','icon','aria-label="Действия с квитанцией"')]
])}${pager(4)}<div class="section">${banner('Квитанция не подтверждает оплату','Результат проверки и статус оплаты отображаются в заказе.')}</div>`}
function orders(){const count=P.role==='supplier'?2:4;return `${tabs(['Все заказы','Требуют действия','В работе','Завершённые'])}<div class="subsummary"><span><strong>${count}</strong> заказа</span><span>Только выбранная организация</span><span>Алматы · время UTC+5</span></div>${toolbar('Номер заказа или контрагент')}${table(['Заказ','Контрагент / дата','Статус заказа','Оплата','Сумма',''],rowsOrders())}${pager(count)}<div class="section">${banner('Статус заказа и статус оплаты показаны отдельно','Открывайте заказ, чтобы увидеть подтверждённые количества, отгрузки и документы. Референс частичного подтверждения показывает более ранний шаг DM-0264.')}</div>`}
function offers(){return `${banner('Договор с площадкой — обязательное условие публикации','Для этой синтетической организации показано тестовое основание. Это не юридическое подписание.')}${tabs(['Все предложения','Опубликованные','Черновики','Требуют внимания'])}${toolbar('Артикул, название или производитель',['Все статусы','Все склады'])}${table(['Предложение','Упаковка','Цена за уп.','Остаток','Обновление','Статус',''],products.map(([name,pack,price,stock],i)=>[link('supplier-offer-editor',name)+`<small>${['CMP-A2-4','ENDO-06','GLOVES-M'][i]} · склад Алматы</small>`,pack,money(price),stock+' уп.',i===2?'Данные устарели':'12 мин назад',badge(i===2?'Нужен остаток':'Опубликовано',i===2?'warn':'good'),link('supplier-offer-editor','Изменить')]))}${pager(3)}<div class="section">${banner('Товар и предложение — разные сущности','Название и свойства описывают товар. Цена, остаток, склад и условия относятся к предложению вашей организации.')}</div>`}
function queue(){return `${tabs(['Требуют решения','В работе','Завершённые'])}<div class="subsummary"><span><strong>3</strong> обращения</span><span>Приоритет определён причиной, а не возрастом карточки</span></div>${toolbar('Заказ, организация или ID операции',['Все причины','За 7 дней'])}${table(['Объект','Причина','Сторона','Создано','Приоритет',''],[
[link('admin-corrections','Карточка CMP-A2-4'),'Исправление упаковки','Демо-поставщик 01','14.09 · 10:15',badge('Нужна проверка','warn'),link('admin-corrections','Рассмотреть')],
[link('admin-imports','Импорт IMP-031'),'2 строки не сопоставлены','Демо-поставщик 01','14.09 · 10:30',badge('Обычный'),link('admin-imports','Сопоставить')],
[link('admin-controls','Допуск организации'),'Нет действующего договора','Демо-поставщик 02','14.09 · 11:00',badge('Блокирует публикацию','warn'),link('admin-controls','Рассмотреть')]
])}${pager(3)}<div class="section two">${panel('Принцип работы',`<p class="muted">Решение применяется к конкретному объекту. Основание, исполнитель и результат остаются в истории.</p>`)}${panel('Перед подтверждением',`<p class="muted">Проверьте организацию, последствия и причину. Разбор обращения не отменяет проверки доступа или договора.</p>`)}</div>`}
function controls(){return `<div class="atlas-grid">${panel('Действия',`<div class="spec-label">Default · hover · focus-visible · pressed</div><div class="spec-row">${btn('Сохранить','notice','primary')}${btn('Наведение','notice','primary hover-demo')}${btn('Фокус','notice','focus-demo')}${btn('Нажато','notice','primary active-demo')}</div><div class="spec-label">Secondary · destructive · disabled · loading</div><div class="spec-row">${btn('Отмена')}${btn('Удалить','danger','danger')}${btn('Недоступно','notice','','disabled')}${btn('Сохранение…','notice','primary','disabled aria-busy="true"')}</div><p>Опасное действие требует явного подтверждения. Disabled сопровождается объяснением причины.</p>`)}${panel('Поля и помощь',`<div class="form-grid">${field('Артикул','CMP-A2-4','Идентификатор товара в учётной системе поставщика.')}${field('Цена за упаковку, ₸','18 900','Стоимость всей упаковки, а не одной единицы внутри неё.')}${field('Количество','2','Число упаковок, которое вы собираетесь заказать.','number')}${select('Единица закупки',['Упаковка','Штука'])}</div><div class="section">${field('Название','', 'Название должно помогать отличить товар от других вариантов.','text','aria-invalid="true" placeholder="Например: композит A2"')}<p class="red">Укажите название товара.</p></div>`)}${panel('Выбор и количество',`<div class="spec-row">${qty(2)}${help('Количество','Значение — черновик. Нажмите «Сохранить количество», чтобы применить его.')}${btn('Сохранить количество','save-qty','primary')}</div>${check('Только в наличии',true)}<hr class="rule">${check('По цене',true,'radio')}${check('По сроку обновления',false,'radio')}<hr class="rule"><div class="switch">${check('Внутренние уведомления',true)}</div><p>Новый остаток не уменьшает выбранное количество молча.</p>`)}${panel('Многострочный ввод и файл',`${field('Причина изменения','Недостаточный остаток','Объясните стороне заказа, почему количество изменилось.','textarea')}<div class="section">${upload()}</div>`)}</div>`}
function overlays(){return `<div class="atlas-grid"><section class="atlas-block"><div class="spec-label">Dialog · открыто / ошибка</div><div class="static-modal"><div class="modal-head"><h3>Загрузить документ</h3></div><div class="modal-body"><p>Документ будет доступен участникам выбранного заказа в пределах их прав.</p>${select('Тип документа',['Счёт','Квитанция','Накладная'])}<div class="section">${field('Номер документа','INV-0264','Номер из самого документа, не номер заказа.')}</div><div class="section">${select('Связанный заказ',['DM-0264 · Демо-поставщик 01'])}</div>${file('invoice.exe','Формат не поддерживается')}<p class="red">Выберите разрешённый формат. Введённые данные сохранены.</p></div><div class="actions">${btn('Отмена','discard')}${btn('Выбрать другой файл','upload','primary')}</div></div></section><section class="atlas-block"><div class="spec-label">Combobox · раскрытый список / поиск</div>${field('Поставщик','','Выбор ограничен доступными организации данными.','search','placeholder="Найти поставщика"')}<div class="open-list" aria-label="Образец списка поставщиков">${Array.from({length:10},(_,i)=>`<button type="button" class="${i===0?'selected':''}" data-action="select-demo">Демо-поставщик ${String(i+1).padStart(2,'0')}${i===0?' · выбран':''}</button>`).join('')}</div><p>Список прокручивается внутри popup; выбранное значение сохраняется при повторном открытии.</p><hr class="rule"><div class="spec-label">Popover · объяснение поля</div><div class="tip-static">Цена за упаковку — стоимость всей упаковки 4 г. Заказ оформляется в упаковках.</div><p>Подсказка доступна наведением, нажатием и клавиатурой. Критические ограничения видны в форме.</p></section><section class="atlas-block"><div class="spec-label">Drawer · детали без потери контекста</div><div class="static-drawer"><h3>Документ INV-0264</h3><p>DM-0264 · Демо-поставщик 01</p>${dl([['Тип','Счёт'],['Сумма',money(55950)],['Статус','Сформирован'],['Оплата','Не подтверждена']])}${file()}<div class="actions end">${link('buyer-document-detail','Открыть полностью','btn')}</div></div></section><section class="atlas-block"><div class="spec-label">Dialog · несохранённые изменения</div><div class="static-modal"><div class="modal-head"><h3>Выйти без сохранения?</h3></div><div class="modal-body"><p>Черновик подтверждения DM-0264 изменён. Несохранённые количества и причина будут потеряны.</p></div><div class="actions">${btn('Продолжить редактирование','notice')}${btn('Выйти без сохранения','discard','danger')}</div></div><div class="section">${btn('Проверить настоящий dialog','edit-dialog','primary')}</div><p>Этот интерактивный пример позволяет проверить Escape, Tab, фокус и защиту ввода. Данные только в памяти вкладки.</p></section></div>`}
function header(){const roles={buyer:'Демо-клиника',supplier:'Демо-поставщик',admin:'Демо-оператор',public:'Гость',auth:'Гость'};const nav=P.role==='admin'?[['admin-overview','Очередь'],['admin-organizations','Организации'],['admin-catalog','Каталог']]:[['public-catalog','Каталог'],[P.role==='supplier'?'supplier-orders':'buyer-orders','Заказы'],[P.role==='supplier'?'supplier-documents':'buyer-documents','Документы']];const menuPages=window.DM_PAGES.filter(x=>x.role===(['auth','public'].includes(P.role)?'public':P.role)&&!x.id.startsWith('components')&&!x.id.startsWith('system'));return `<header class="header" id="header"><div class="header-inner">${link('public-home','DentMarket','logo')}<div class="dropdown location-slot"><button type="button" class="location" data-menu="city" aria-expanded="false">${icon('Location')}Алматы${icon('ChevronDown')}</button><div id="city-menu" class="menu" hidden><p class="meta">Город поставки</p>${['Алматы','Астана','Шымкент'].map(x=>`<button type="button" data-action="city">${x}</button>`).join('')}</div></div><div class="search">${icon('Search')}<input type="search" aria-label="Поиск по каталогу" placeholder="Название, артикул или производитель">${help('Поиск по каталогу','Ищите по названию, артикулу или производителю. В прототипе нет рабочего API-поиска.')}</div><nav aria-label="Основная навигация">${nav.map(([id,name])=>link(id,name,id===P.id||P.id.includes(id.split('-').pop())?'active':'')).join('')}<div class="dropdown"><button type="button" data-menu="more" aria-label="Разделы приложения" aria-expanded="false"><span class="more-label">Ещё ${icon('ChevronDown')}</span><span class="more-mobile">${icon('Navigation')}</span></button><div id="more-menu" class="menu" hidden><p class="meta">${roles[P.role]} · разделы</p>${menuPages.map(x=>link(x.id,x.title)).join('')}</div></div></nav>${link(P.role==='supplier'?'supplier-offers':P.role==='admin'?'admin-audit':'buyer-cart',icon(P.role==='supplier'?'Box':P.role==='admin'?'ShieldLock':'Cart')+(P.role==='supplier'?' Предложения':P.role==='admin'?' Журнал':' Корзина · 3'),'context')}<div class="dropdown"><button type="button" class="profile" data-menu="profile" aria-label="Профиль и организация" aria-expanded="false">${icon('Person')}<span>${roles[P.role]}</span>${icon('ChevronDown')}</button><div id="profile-menu" class="menu" hidden><p><strong>${roles[P.role]} 01</strong><br><small>Синтетическая организация</small></p>${link('account','Организация и реквизиты')}${link('team','Команда и доступ')}${btn('Сменить организацию','organization','quiet')}${btn('Город: Алматы','choose-city','quiet')}${link('auth-login','Войти / выйти из прототипа')}</div></div></div></header>`}
const subtitles={documents:'Договоры, счета и документы по вашим заказам',orders:'Подтверждение, оплата и получение — отдельные этапы',offers:'Ваши цены, упаковки, склады и актуальность данных',queue:'Проблемные операции и решения с сохранением истории',controls:'Одна система размеров, типографики и обратной связи',overlays:'Модальные окна, списки и подсказки показаны раскрытыми'};
function title(){const auth=P.role==='auth'||['marketing','about','supplier-marketing'].includes(P.template);if(auth)return '';return `<div class="title-row"><div><h1>${P.title}</h1><p>${subtitles[P.template]||'Демо-клиника 01 · Демо-поставщик 01 · Алматы'}</p></div><div class="title-actions"><span class="demo">Демонстрационные данные</span>${P.action&&!['catalog','product','cart','supplier-order','order-detail','document-detail','payment'].includes(P.template)?btn((['documents','offers'].includes(P.template)?icon('Add')+' ':'')+P.action,P.template==='documents'?'upload':P.template==='offers'?'offer':P.template==='orders'?'order':'notice','primary'):''}</div></div>`}
const renders={documents,orders,offers,queue,controls,overlays};
function render(){const body=(renders[P.template]||window.DM_EXTRA?.[P.template]);document.title=P.title+' · DentMarket / макет';document.getElementById('app').innerHTML=header()+`<main id="main" class="page">${title()}${body?body():banner('Шаблон ещё не создан',P.template,'warn')}</main><footer class="prototype-footer"><span>Визуальный прототип · ${P.id} · ${P.role} · default · v${P.version} · PROPOSED<br>Не подключён к API. Данные синтетические. Макет не подтверждает готовность функции.</span><a href="index.html">Все референсы →</a></footer>`;}
let dirty=false,returnFocus=null;const dialog=document.getElementById('dialog');
dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=Array.from(dialog.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')).filter(x=>x.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}});
dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)){dialogDraft=rememberDraft();closeDialog()}});
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.hidden=true,6500)}
function openDialog(kind){returnFocus=document.activeElement;dirty=false;const bodies={city:['Город поставки',select('Город',['Алматы','Астана','Шымкент'],'Город используется при подборе предложений.'),'Выбрать'],upload:[`Загрузить документ`,`${select('Тип документа',['Счёт','Квитанция','Накладная'])}${field('Номер','INV-0264','Номер из документа.')}${select('Заказ',['DM-0264 · Демо-поставщик 01'])}${upload()}`,'Проверить файл'],edit:[`Изменить подтверждение`,`${field('Количество упаковок','2','Нажмите сохранить для применения.','number')}${field('Причина','Недостаточный остаток','Причина изменения передаётся клинике.','textarea')}`,'Сохранить черновик'],danger:['Подтвердите действие',`<p>Удаление допустимо только для разрешённого черновика. Исторические документы и записи заказа этим действием не удаляются.</p>${field('Причина','','Объясните, почему черновик больше не нужен.','textarea')}`,'Удалить черновик'],organization:['Выбор организации',`${select('Организация',['Демо-клиника 01','Демо-клиника 02'])}${banner('Права будут проверены заново','Этот прототип не создаёт сессию и не переключает tenant в рабочем приложении.')}`,'Выбрать'],menu:['Действия с документом',`${file()}<div class="section actions">${link(P.role==='supplier'?'supplier-document-detail':'buyer-document-detail','Просмотреть','btn')}${btn('Скачать PDF','download')}${link('buyer-order-detail','Открыть заказ','btn')}</div>`,'Закрыть']};const [name,body,primary]=bodies[kind]||bodies.edit;dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${name}</h2>${btn(icon('Dismiss'),'close','icon','aria-label="Закрыть окно"')}</div><div class="dialog-body">${body}</div><div class="dialog-actions">${btn('Отмена','close')}${btn(primary,'dialog-save','primary')}</div>`;dialog.showModal();dialog.querySelector('input,select,textarea,button').focus()}
function closeDialog(){if(dirty){dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">Выйти без сохранения?</h2></div><div class="dialog-body"><p>Введённые данные будут потеряны. Сервер и рабочие документы не изменялись.</p></div><div class="dialog-actions">${btn('Продолжить редактирование','back-edit')}${btn('Выйти без сохранения','force-close','danger')}</div>`;dialog.querySelector('button').focus()}else{dialog.close();returnFocus?.focus()}}
function rememberDraft(){const clone=dialog.cloneNode(true);const live=dialog.querySelectorAll('input,select,textarea');clone.querySelectorAll('input,select,textarea').forEach((el,i)=>{if(el.tagName==='TEXTAREA')el.textContent=live[i].value;else if(el.tagName==='SELECT')Array.from(el.options).forEach((o,j)=>o.toggleAttribute('selected',live[i].selectedIndex===j));else el.setAttribute('value',live[i].value)});return clone.innerHTML}let dialogDraft='';dialog.addEventListener('input',()=>{dirty=true});dialog.addEventListener('cancel',e=>{e.preventDefault();dialogDraft=rememberDraft();closeDialog()});
document.addEventListener('click',e=>{const h=e.target.closest('.help');if(h){h.setAttribute('aria-expanded',String(h.getAttribute('aria-expanded')!=='true'));return}const mb=e.target.closest('[data-menu]');if(mb){const menu=document.getElementById(mb.dataset.menu+'-menu');const open=menu.hidden;document.querySelectorAll('.menu').forEach(x=>x.hidden=true);document.querySelectorAll('[data-menu]').forEach(x=>x.setAttribute('aria-expanded','false'));menu.hidden=!open;mb.setAttribute('aria-expanded',String(open));return}if(!e.target.closest('.menu')){document.querySelectorAll('.menu').forEach(x=>x.hidden=true);document.querySelectorAll('[data-menu]').forEach(x=>x.setAttribute('aria-expanded','false'))}const tab=e.target.closest('[data-tab]');if(tab){tab.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-selected',String(x===tab)));toast(`Выбрано «${tab.dataset.tab}». Это демонстрация состояния вкладки, не запрос к API.`);return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(['plus','minus'].includes(a)){const input=b.closest('.qty').querySelector('input');input.value=Math.max(0,Number(input.value)+(a==='plus'?1:-1));toast('Количество изменено в черновике. Сохраните его явно.');return}if(a==='upload'){openDialog('upload');return}if(a==='edit-dialog'){openDialog('edit');return}if(a==='danger'){openDialog('danger');return}if(a==='organization'){openDialog('organization');return}if(a==='choose-city'){openDialog('city');return}if(a==='document-menu'){openDialog('menu');return}if(a==='offer'){location.href='preview.html?page=supplier-offer-editor';return}if(a==='order'){location.href='preview.html?page=buyer-order-detail';return}if(a==='close'){dialogDraft=rememberDraft();closeDialog();return}if(a==='force-close'){dirty=false;closeDialog();return}if(a==='back-edit'){dialog.innerHTML=dialogDraft;dialog.querySelector('input,select,textarea,button')?.focus();return}if(a==='dialog-save'){dirty=false;closeDialog();toast('Прототип: действие показано. Файл, документ и данные не отправлялись на сервер.');return}if(a==='filter'){const text=document.querySelector('[data-filter]')?.value.toLowerCase()||'';document.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(text));toast('Показан локальный фильтр синтетических строк.');return}if(a==='reset'){document.querySelectorAll('[data-filter]').forEach(x=>x.value='');document.querySelectorAll('tbody tr').forEach(x=>x.hidden=false);return}if(a==='city'){toast('Выбран город '+b.textContent+'. Изменение только демонстрационное.');b.closest('.menu').hidden=true;return}if(a==='filter-toggle'){b.closest('.filters').classList.toggle('is-open');return}if(a==='download'){toast('Скачивание не выполняется: это визуальный образец, а не сформированный документ.');return}toast(a==='save-qty'?'Черновик показан как сохранённый только в прототипе. Рабочая корзина не менялась.':'Демонстрация интерфейса: действие не отправляется в API.');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open){document.querySelectorAll('.menu').forEach(x=>x.hidden=true);const open=document.querySelector('[data-menu][aria-expanded=true]');open?.setAttribute('aria-expanded','false');open?.focus();document.querySelectorAll('.help').forEach(x=>x.setAttribute('aria-expanded','false'))}});
document.addEventListener('submit',e=>{e.preventDefault();toast('Демонстрационная форма: данные не отправлены.')});
let previous=0;document.addEventListener('scroll',()=>{const y=scrollY,h=document.getElementById('header');const held=h.contains(document.activeElement)||Array.from(h.querySelectorAll('.menu')).some(x=>!x.hidden)||dialog.open;const hidden=y>80&&y>previous&&!held;h.classList.toggle('hidden',hidden);h.inert=hidden;previous=y},{passive:true});
window.DM_HELPERS={icon,esc,link,btn,badge,help,field,select,check,banner,panel,dl,table,tabs,toolbar,pager,money,doc,qty,steps,file,upload,timeline,party,products,itemRows};
const extra=document.createElement('script');extra.src='templates.js';extra.onload=render;extra.onerror=render;document.head.append(extra);
