// Source-backed surface inventory. All output is design PROPOSED, not runtime proof.
window.DM_PAGES = [
// id, role, title, template, source, route/surface, current implementation, primary action
['public-home','public','Закупки без лишних звонков','marketing','apps/landing-web/app/page.tsx','landing:/','PARTIAL','Открыть каталог'],
['public-about','public','О DentMarket','about','apps/buyer-web/app/about/page.tsx','buyer:/about','PARTIAL','Перейти в каталог'],
['public-suppliers','public','Ваш ассортимент — в закупках клиник','supplier-marketing','apps/buyer-web/app/suppliers/page.tsx','buyer:/suppliers','PARTIAL','Стать поставщиком'],
['public-catalog','buyer','Стоматологические материалы','catalog','apps/buyer-web/app/catalog/page.tsx','buyer:/catalog; / active=catalog','PARTIAL','Сравнить предложения'],
['product-offers','buyer','Композит универсальный A2','product','apps/buyer-web/app/products/[id]/page.tsx','buyer:/products/[id]; product dialog','PARTIAL','В корзину'],
['buyer-cart','buyer','Корзина','cart','apps/buyer-web/app/features/purchasing/buyer-cart.tsx','buyer:/ active=cart; target /cart','SCOPED_ACCEPTED','Принять изменения'],
['buyer-checkout','buyer','Проверка заказа','checkout','actual_docs/product/DENTMARKET_PRODUCT_V2.md','target buyer:/checkout; current cart action','TARGET','Оформить заказ'],
['buyer-orders','buyer','Заказы клиники','orders','apps/buyer-web/app/features/purchasing/buyer-orders.tsx','buyer:/ active=orders; target /orders','PARTIAL','Открыть заказ'],
['buyer-order-detail','buyer','Заказ № DM-0264','order-detail','apps/buyer-web/app/order-decision-details.tsx','order details inside buyer orders','PARTIAL','Открыть документы'],
['buyer-documents','buyer','Документы','documents','apps/buyer-web/app/documents/page.tsx','buyer:/documents','PARTIAL','Загрузить документ'],
['buyer-document-detail','buyer','Счёт № INV-0264','document-detail','packages/ui/src/document-archive.tsx','buyer:/documents → detail dialog','PARTIAL','Скачать PDF'],
['buyer-document-upload','buyer','Загрузка документа','document-upload','packages/ui/src/document-archive.tsx','buyer:/documents → upload dialog','PARTIAL','Загрузить документ'],
['buyer-workspace','buyer','Списки и бюджеты','workspace','apps/buyer-web/app/buyer-services-panel.tsx','buyer:/ active=workspace','PARTIAL','Создать список'],
['buyer-notifications','buyer','Уведомления','notifications','apps/buyer-web/app/page.tsx','buyer:/ active=notifications','PARTIAL','Отметить прочитанными'],
['buyer-support','buyer','Поддержка','support','apps/buyer-web/app/buyer-services-panel.tsx','buyer:/ active=support','PARTIAL','Создать обращение'],
['buyer-assistant','buyer','AI-помощник','assistant','apps/buyer-web/app/buyer-services-panel.tsx','buyer:/ active=assistant; local go_live','CONDITIONAL','Отправить'],
['buyer-recommendations','buyer','Варианты поставки','recommendations','apps/buyer-web/app/smart-commerce-panel.tsx','buyer:/ active=smart-commerce; local go_live','CONDITIONAL','Подобрать предложения'],
['buyer-reviews','buyer','Отзыв о поставщике','reviews','apps/buyer-web/app/page.tsx','review action inside order; trust flag','CONDITIONAL','Отправить отзыв'],
['account','buyer','Организация и реквизиты','account','actual_docs/product/DENTMARKET_PRODUCT_V2.md','target buyer:/account','TARGET','Сохранить реквизиты'],
['team','buyer','Команда и доступ','team','actual_docs/backend/DENTMARKET_BACKEND_FOUNDATION_V2.md','CORE-05; account/team target','TARGET','Пригласить сотрудника'],
['supplier-dashboard','supplier','Обзор поставщика','dashboard','apps/supplier-web/app/features/supplier-workspace/supplier-dashboard.tsx','supplier:/ active=dashboard','PARTIAL','Перейти к заказам'],
['supplier-onboarding','supplier','Подготовка к публикации','onboarding','apps/supplier-web/app/onboarding-progress.tsx','supplier:/ onboarding panel','PARTIAL','Открыть договор'],
['supplier-orders','supplier','Заказы поставщику','orders','apps/supplier-web/app/features/supplier-workspace/supplier-orders.tsx','supplier:/ active=orders','PARTIAL','Открыть заказ'],
['supplier-order-detail','supplier','Заказ № DM-0264','supplier-order','apps/supplier-web/app/order-confirmation-panel.tsx','supplier order confirmation dialog','PARTIAL','Подтвердить частично'],
['supplier-shipment','supplier','Отгрузка заказа DM-0264','shipment','apps/supplier-web/app/shipment-panel.tsx','supplier order → shipment panel','PARTIAL','Подтвердить отгрузку'],
['supplier-offers','supplier','Предложения','offers','apps/supplier-web/app/features/supplier-workspace/supplier-offers.tsx','supplier:/ active=offers','PARTIAL','Создать предложение'],
['supplier-offer-editor','supplier','Предложение: композит A2','offer-editor','apps/supplier-web/app/features/supplier-workspace/supplier-offers.tsx','manual create/edit; CORE-04 acceptance open','PARTIAL','Сохранить черновик'],
['supplier-inventory','supplier','Остатки и актуальность','inventory','apps/supplier-web/app/features/supplier-workspace/supplier-inventory.tsx','supplier:/ active=inventory','PARTIAL','Сохранить остаток'],
['supplier-imports','supplier','Загрузка товаров','imports','apps/supplier-web/app/features/supplier-workspace/supplier-integrations.tsx','supplier:/ active=integrations','PARTIAL','Загрузить прайс'],
['supplier-import-review','supplier','Проверка прайса','import-review','apps/supplier-web/app/features/supplier-workspace/supplier-integrations.tsx','import batch → rows/matching','PARTIAL','Сопоставить строку'],
['supplier-connectors','supplier','Учётные системы','connectors','apps/supplier-web/app/connector-onboarding.tsx','supplier integrations → connector onboarding','CONDITIONAL','Проверить подключение'],
['supplier-compliance','supplier','Документы поставщика','compliance','apps/supplier-web/app/features/supplier-workspace/supplier-compliance.tsx','supplier:/ active=compliance','PARTIAL','Загрузить подтверждение'],
['supplier-agreement','supplier','Договор с DentMarket','agreement','apps/supplier-web/app/marketplace-agreement-panel.tsx','supplier onboarding → marketplace agreement','CONDITIONAL','Открыть документ'],
['supplier-corrections','supplier','Исправления карточек','corrections','apps/supplier-web/app/product-corrections-panel.tsx','supplier offer → correction panel','PARTIAL','Отправить исправление'],
['supplier-documents','supplier','Документы','documents','apps/supplier-web/app/documents/page.tsx','supplier:/documents','PARTIAL','Загрузить документ'],
['supplier-document-detail','supplier','Счёт № INV-0264','document-detail','packages/ui/src/document-archive.tsx','supplier:/documents → detail dialog','PARTIAL','Скачать PDF'],
['supplier-promotions','supplier','Акции и продвижение','promotions','apps/supplier-web/app/promotions-panel.tsx','supplier:/ active=promotions; local go_live','CONDITIONAL','Создать акцию'],
['supplier-trust','supplier','Отзывы и география','trust','apps/supplier-web/app/supplier-trust-panel.tsx','supplier:/ active=trust; local go_live','CONDITIONAL','Ответить на отзыв'],
['billing','supplier','Услуги платформы','billing','actual_docs/product/DENTMARKET_OUT_OF_PILOT_FEATURES.md','billing backend exists; complete frontend not accepted','TARGET','Посмотреть условия'],
['admin-overview','admin','Рабочая очередь','queue','apps/admin-web/app/operation-queue.tsx','admin:/ active=overview or orders','PARTIAL','Разобрать обращение'],
['admin-organizations','admin','Организации','organizations','apps/admin-web/app/resource-lists.tsx','admin:/ active=organizations','PARTIAL','Создать организацию'],
['admin-organization-create','admin','Новая организация','organization-create','apps/admin-web/app/organization-quick-create.tsx','admin organization quick-create dialog','PARTIAL','Создать организацию'],
['admin-access','admin','Пользователи и права','team','apps/admin-web/app/foundation-management.tsx','admin:/ active=organizations/access','PARTIAL','Назначить роль'],
['admin-catalog','admin','Мастер-карточки и варианты','catalog-admin','apps/admin-web/app/catalog-foundation.tsx','admin:/ active=catalog','PARTIAL','Создать карточку'],
['admin-taxonomy','admin','Атрибуты каталога','taxonomy','apps/admin-web/app/foundation-management.tsx','admin organizations → attributes/category rules','PARTIAL','Добавить атрибут'],
['admin-catalog-quality','admin','Качество каталога','quality','apps/admin-web/app/catalog-quality.tsx','admin:/ active=catalog → quality','PARTIAL','Открыть проблемные карточки'],
['admin-corrections','admin','Проверка исправлений','corrections-review','apps/admin-web/app/product-correction-queue.tsx','admin:/ active=catalog → corrections','PARTIAL','Принять исправление'],
['admin-imports','admin','Сопоставление товаров','import-review','apps/admin-web/app/catalog-import-review.tsx','admin:/ active=imports → review','PARTIAL','Подтвердить сопоставление'],
['admin-supply','admin','Предложение и публикация','offer-editor','apps/admin-web/app/supplier-operations.tsx','admin:/ active=imports → supplier operations','PARTIAL','Проверить готовность'],
['admin-lots','admin','Партии и резервы','lots','apps/admin-web/app/supplier-operations.tsx','admin imports → lots/reservations','PARTIAL','Открыть резерв'],
['admin-connectors','admin','Подключения и ошибки','connectors','apps/admin-web/app/integration-operations.tsx','admin:/ active=imports → integrations','CONDITIONAL','Открыть подключение'],
['admin-connector-readiness','admin','Готовность коннекторов','readiness','apps/admin-web/app/connector-readiness-registry.tsx','admin imports → readiness registry','PARTIAL','Открыть проверку'],
['admin-agreements','admin','Договоры с поставщиками','agreements','apps/admin-web/app/agreement-operations.tsx','admin:/ active=orders → agreements','CONDITIONAL','Открыть договор'],
['admin-controls','admin','Допуск поставщиков','supplier-controls','apps/admin-web/app/supplier-controls.tsx','admin:/ active=access → controls','PARTIAL','Рассмотреть допуск'],
['admin-assurance','admin','Готовность и ограничения','readiness','apps/admin-web/app/platform-assurance.tsx','admin:/ active=access → assurance','PARTIAL','Открыть проверку'],
['admin-trust','admin','Риски и апелляции','trust-ops','apps/admin-web/app/trust-operations.tsx','admin:/ active=security; trust enabled','CONDITIONAL','Рассмотреть обращение'],
['admin-audit','admin','Журнал действий','audit','apps/admin-web/app/audit-operations.tsx','admin:/ active=security → audit','PARTIAL','Применить фильтры'],
['admin-settings','admin','Настройки платформы','settings','apps/admin-web/app/platform-settings.tsx','admin:/ active=settings','PARTIAL','Обновить сведения'],
['admin-metrics','admin','Операционные показатели','metrics','apps/admin-web/app/live-metrics.tsx','admin:/ overview → live metrics','PARTIAL','Обновить показатели'],
['manual-payment','buyer','Подтверждение оплаты','payment','actual_docs/product/DENTMARKET_PRODUCT_V2.md','CORE-02 proposal; not a live route','TARGET','Отправить на проверку'],
['auth-login','auth','Вход в DentMarket','login','apps/landing-web/app/login/page.tsx','landing:/login; buyer:/login redirects','PARTIAL','Войти'],
['auth-register','auth','Создать аккаунт','register','apps/landing-web/app/register/page.tsx','landing:/register?role=buyer|supplier','PARTIAL','Продолжить'],
['auth-resume','auth','Продолжить регистрацию','resume','apps/landing-web/app/register/resume/page.tsx','landing:/register/resume','SCOPED_ACCEPTED','Продолжить'],
['auth-verify','auth','Подтверждение почты','verify','apps/landing-web/app/verify-email/page.tsx','landing:/verify-email','PARTIAL','Перейти ко входу'],
['auth-reset','auth','Восстановление доступа','reset','apps/landing-web/app/reset-password/page.tsx','landing:/reset-password','PARTIAL','Сохранить пароль'],
['auth-admin','auth','Вход оператора','admin-login','apps/admin-web/app/login/page.tsx','admin:/login with MFA','SCOPED_ACCEPTED','Подтвердить вход'],
['legal-terms','public','Условия использования','legal','apps/landing-web/app/legal/terms/page.tsx','landing:/legal/terms','PARTIAL','Вернуться'],
['legal-privacy','public','Конфиденциальность','legal','apps/landing-web/app/legal/privacy/page.tsx','landing:/legal/privacy','PARTIAL','Вернуться'],
['system-empty','buyer','Заказы клиники','empty','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','shared empty/first use','PARTIAL','Открыть каталог'],
['system-error','buyer','Не удалось загрузить документы','error','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','shared async error','PARTIAL','Повторить'],
['system-forbidden','buyer','Недостаточно прав','forbidden','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','shared403','PARTIAL','Выбрать организацию'],
['system-session','buyer','Войдите снова','session','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','expired session during work','PARTIAL','Войти'],
['system-not-found','public','Страница не найдена','not-found','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','framework404; custom composition proposed','TARGET','Открыть каталог'],
['system-loading','buyer','Документы','loading','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','shared loading skeleton','PARTIAL',''],
['components-controls','buyer','Компоненты · ввод и действия','controls','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','component atlas; not app route','DESIGN',''],
['components-overlays','buyer','Компоненты · раскрытые элементы','overlays','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','component atlas; modal/select/popover','DESIGN',''],
['components-feedback','buyer','Компоненты · состояния','feedback','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','component atlas; not app route','DESIGN',''],
['components-navigation','buyer','Компоненты · навигация','navigation','actual_docs/ui-ux/UI_UX_IMPLEMENTATION_STANDARD.md','header/city/org/menu/table controls','DESIGN','']
].map(([id,role,title,template,source,route,implementation,action])=>({id,role,title,template,source,route,implementation,action,design:'PROPOSED',version:'1.0',states:['default','loading','empty','error','permission'],created:true,reviewed:false}));
