ALTER TYPE "SupplierDataSourceType" ADD VALUE IF NOT EXISTS 'PDF';
ALTER TYPE "ImportBatchStatus" ADD VALUE IF NOT EXISTS 'REVIEW_REQUIRED';
ALTER TYPE "OrganizationCredentialType" ADD VALUE IF NOT EXISTS 'MEDICAL_DEVICE_SALE_NOTIFICATION';
ALTER TABLE "ImportBatch" ADD COLUMN IF NOT EXISTS "extractionMetadata" JSONB;

INSERT INTO "ComplianceRule" ("id", "code", "version", "name", "regulatoryClass", "riskLevel", "decision", "priority", "conditions", "requiredCredentialTypes", "disclosureText", "status", "effectiveFrom", "updatedAt") VALUES
('00000000-0000-4000-8000-000000009101', 'KZ.MEDICAL_DEVICE.LOW_RISK', 1, 'Реализация медицинских изделий низкого риска', 'medical-device-low-risk', 'ORANGE', 'ALLOWED_WITH_DISCLOSURE', 10, '{"when":{"sellerCapabilitiesAny":["SUPPLIER"]},"requirements":{"lotRequired":true,"registrationCertificateRequired":true,"verifiedOriginRequired":true,"requiredCredentialAnyOf":[["WHOLESALE_LICENSE","MEDICAL_DEVICE_SALE_NOTIFICATION"]]}}', '[]', 'Требования применяются по настраиваемому compliance-правилу; оператор подтверждает применимость разрешительного режима.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('00000000-0000-4000-8000-000000009102', 'KZ.MEDICAL_DEVICE.IMPLANTABLE', 1, 'Реализация имплантируемых медицинских изделий', 'medical-device-implantable', 'RED', 'ALLOWED_WITH_DISCLOSURE', 5, '{"when":{"sellerCapabilitiesAny":["SUPPLIER"]},"requirements":{"lotRequired":true,"registrationCertificateRequired":true,"serialNumberRequired":true,"verifiedOriginRequired":true,"requiredCredentialAnyOf":[["WHOLESALE_LICENSE","MEDICAL_DEVICE_SALE_NOTIFICATION"]]}}', '[]', 'Имплантируемое изделие требует проверки регистрации, партии, происхождения и разрешительного основания продавца.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('00000000-0000-4000-8000-000000009103', 'KZ.MEDICAL_EQUIPMENT', 1, 'Реализация медицинского оборудования', 'medical-equipment', 'ORANGE', 'ALLOWED_WITH_DISCLOSURE', 20, '{"when":{"sellerCapabilitiesAny":["SUPPLIER"]},"requirements":{"registrationCertificateRequired":true,"verifiedOriginRequired":true,"requiredCredentialAnyOf":[["WHOLESALE_LICENSE","MEDICAL_DEVICE_SALE_NOTIFICATION"]]}}', '[]', 'Медицинское оборудование публикуется после проверки регистрационных и товаросопроводительных данных.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("code", "version") DO NOTHING;
