import {test,expect,type Page} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import path from 'node:path';
import {writeFile} from 'node:fs/promises';
test.skip(process.env.E2E_DOCUMENT_UPLOAD_LIVE!=='true','Approved isolated audit environment required');
let child:ChildProcess,counter=0;const requests=new Map<number,{resolve(value:unknown):void;reject(error:Error):void}>();
function fixture<T>(type:string,details:Record<string,unknown>={}):Promise<T>{return new Promise((resolve,reject)=>{const id=++counter,timer=setTimeout(()=>{requests.delete(id);reject(Error('Document fixture IPC timeout'));},30000);requests.set(id,{resolve:v=>{clearTimeout(timer);resolve(v as T);},reject:e=>{clearTimeout(timer);reject(e);}});child.send({id,type,...details});});}
test.beforeAll(async()=>{child=spawn(process.execPath,[path.resolve('../../scripts/verify-document-upload.mjs')],{windowsHide:true,stdio:['ignore','ignore','ignore','ipc']});await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Document runtime startup timeout')),75000);child.once('exit',code=>{clearTimeout(timer);reject(Error(`Owned document fixture exited ${code}`));});child.on('message',(m:{type?:string;id?:number;value?:unknown;error?:string})=>{if(m.type==='startup-diagnostics'){console.error(JSON.stringify(m.value));return;}if(m.type==='ready'){clearTimeout(timer);resolve();return;}if(m.id){const request=requests.get(m.id);requests.delete(m.id);if(m.error)request?.reject(Error(m.error));else request?.resolve(m.value);}});});await fixture('prepare');});
test.afterAll(async()=>{if(!child||child.exitCode!==null)return;await new Promise<void>(resolve=>{const timer=setTimeout(resolve,15000);child.once('exit',()=>{clearTimeout(timer);resolve();});if(child.connected)child.disconnect();});if(child.exitCode===null)child.kill();});
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){await page.screenshot({path:info.outputPath('failure.png'),fullPage:true}).catch(()=>undefined);await writeFile(info.outputPath('failure-aria.txt'),await page.locator('body').ariaSnapshot()).catch(()=>undefined);}await page.goto('about:blank');});
type Setup={runId:string;number:string;pdf:string;organizationId:string;handoff:object};
type Readback={organizationId:string;documents:{id:string;amountMinor:string;currency:string;documentNumber:string;checksumSha256:string;byteSize:number;status:string;requiredSignatureCount:number;audit:number;outbox:number}[]};
async function open(page:Page,key:string){const data=await fixture<Setup>('setup',{key});const port=key==='supplier'?3102:3101;await page.goto(`http://127.0.0.1:${port}/documents#session=${encodeURIComponent(JSON.stringify(data.handoff))}`);await expect(page).toHaveURL(`http://127.0.0.1:${port}/documents`);await expect(page.getByRole('heading',{name:'Документы',exact:true})).toBeVisible();return data;}
async function fill(page:Page,data:Setup){await page.getByRole('button',{name:'Загрузить документ',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel(/^Тип документа\s*\*?$/).selectOption('OTHER');await dialog.getByLabel(/^Название\s*\*?$/).fill('AUD07 Тестовый файл');await dialog.getByLabel(/^Номер\s*\*?$/).fill(data.number);await dialog.getByLabel('Файл PDF или DOCX',{exact:true}).setInputFiles({name:'audit07.pdf',mimeType:'application/pdf',buffer:Buffer.from(data.pdf,'base64')});return dialog;}
async function readback(key:string,name:string){const result=await fixture<Readback>('readback',{key});await writeFile(test.info().outputPath(name+'.json'),JSON.stringify(result,null,2));return result;}

for(const [key,amount,minor] of [['buyer','1,25','125'],['supplier','90071992547409,93','9007199254740993']])test(`real ${key} upload preserves exact money, draft, focus and pending guard`,async({page})=>{
 await page.setViewportSize(key==='buyer'?{width:1440,height:900}:{width:390,height:844});const data=await open(page,key!);const dialog=await fill(page,data),money=dialog.getByLabel('Сумма (KZT)',{exact:true}),file=dialog.getByLabel('Файл PDF или DOCX',{exact:true}),submit=dialog.getByRole('button',{name:'Загрузить',exact:true});
 await expect(dialog.getByRole('group',{name:'Связанный заказ',exact:true}).getByRole('alert')).toContainText('Нет доступа к списку');
 await money.fill('1,250');await expect(submit).toBeDisabled();await expect(dialog).toContainText('Не более двух знаков');await money.fill(amount!);
 if(key==='buyer'){
  await file.setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('test')});await expect(submit).toBeDisabled();await expect(dialog).toContainText('Поддерживаются только PDF и DOCX');
  await file.setInputFiles({name:'huge.pdf',mimeType:'application/pdf',buffer:Buffer.alloc(10_000_001)});await expect(submit).toBeDisabled();await expect(dialog).toContainText('не должен превышать 10 МБ');
  await file.setInputFiles({name:'audit07.pdf',mimeType:'application/pdf',buffer:Buffer.from(data.pdf,'base64')});
 }
 await money.focus();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await expect(page.getByRole('button',{name:'Загрузить документ',exact:true})).toBeFocused();await page.getByRole('button',{name:'Загрузить документ',exact:true}).click();await expect(money).toHaveValue(amount!);await expect(dialog).toContainText('Выбран: audit07.pdf');expect(await file.evaluate((input:HTMLInputElement)=>input.files?.[0]?.name)).toBe('audit07.pdf');await expect(submit).toBeEnabled();
 await expect(dialog).toHaveCSS('opacity','1');await page.screenshot({path:test.info().outputPath(`${key}-upload-draft.png`),animations:'disabled'});
 let release!:()=>void,seen!:()=>void,count=0;const hold=new Promise<void>(r=>release=r),captured=new Promise<void>(r=>seen=r);
 await page.route('**/documents/upload',async route=>{count++;expect(route.request().postDataJSON()).toMatchObject({amountMinor:minor,currency:'KZT',ownerOrganizationId:data.organizationId});seen();await hold;await route.continue();});
 const response=page.waitForResponse(r=>r.url().endsWith('/documents/upload')&&r.request().method()==='POST');await submit.click();await captured;await expect(dialog.getByRole('button',{name:'Загружаем…',exact:true})).toBeDisabled();await expect(money).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Закрыть, сохранив черновик',exact:true})).toBeDisabled();release();expect((await response).status()).toBe(201);await expect(dialog).toBeHidden();await expect(page.getByRole('button',{name:'Загрузить документ',exact:true})).toBeFocused();await expect(page.getByRole('status').filter({hasText:'Документ загружен в архив.'})).toBeVisible();expect(count).toBe(1);
 const persisted=await readback(key!,'stored');expect(persisted.documents).toHaveLength(1);expect(persisted.documents[0]).toMatchObject({amountMinor:minor,currency:'KZT',documentNumber:data.number,status:'GENERATED',requiredSignatureCount:0,audit:1,outbox:1});expect(persisted.documents[0]!.checksumSha256).toHaveLength(64);expect(persisted.documents[0]!.byteSize).toBe(Buffer.from(data.pdf,'base64').length);
 await expect(page.getByRole('row').filter({hasText:data.number})).toContainText(key==='buyer'?'1,25 ₸':/90\s071\s992\s547\s409,93\s₸/);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать AUD07 Тестовый файл',exact:true}).click();expect((await download).suggestedFilename()).toBe('audit07.pdf');
});

test('real permission and payment-basis rejections preserve draft with safe feedback',async({page})=>{
 await page.setViewportSize({width:1440,height:900});let data=await open(page,'restricted');let dialog=await fill(page,data);const response403=page.waitForResponse(r=>r.url().endsWith('/documents/upload')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Загрузить',exact:true}).click();expect((await response403).status()).toBe(403);await expect(dialog.getByRole('alert',{name:'Ошибка загрузки документа'})).toContainText('Недостаточно прав');await expect(dialog.getByRole('alert',{name:'Ошибка загрузки документа'})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();await page.getByRole('button',{name:'Загрузить документ',exact:true}).click();await expect(dialog.getByLabel(/^Номер\s*\*?$/)).toHaveValue(data.number);expect((await readback('restricted','forbidden-no-write')).documents).toHaveLength(0);
 await page.goto('about:blank');data=await open(page,'buyer');dialog=await fill(page,{...data,number:data.number+'-unpaid'});await dialog.getByLabel(/^Тип документа\s*\*?$/).selectOption('PAYMENT_CONFIRMATION');const response409=page.waitForResponse(r=>r.url().endsWith('/documents/upload')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Загрузить',exact:true}).click();expect((await response409).status()).toBe(409);await expect(dialog.getByRole('alert',{name:'Ошибка загрузки документа'})).toContainText('конфликт');await expect(dialog.getByRole('alert',{name:'Ошибка загрузки документа'})).toBeFocused();await expect(dialog.getByLabel(/^Номер\s*\*?$/)).toHaveValue(data.number+'-unpaid');await page.screenshot({path:test.info().outputPath('actual409-upload-error.png'),animations:'disabled'});await page.keyboard.press('Escape');await expect(dialog).toBeHidden();expect((await readback('buyer','payment-basis-no-new-document')).documents).toHaveLength(1);
});
