import {describe,it,expect} from 'vitest';
import {createRelationRequestSequence,documentAgreementOptions,documentOrderOptions,documentRelationError} from './document-relations';
const org={id:'supplier',displayName:'Мед Снаб',legalName:'ТОО Мед Снаб'};
const order={id:'opaque-id',orderNumber:'DM-001',status:'CONFIRMED',createdAt:'2026-09-16T00:00:00Z',buyerOrganizationId:'buyer',supplierOrganizationId:'supplier',supplier:org,buyer:{...org,id:'buyer',displayName:'Клиника'}};
const contract={id:'opaque-contract',category:'CONTRACT',documentNumber:'ДГ-12',title:'Договор поставки',version:2,status:'DRAFT',documentDate:order.createdAt,participants:[{organizationId:'supplier',organization:org}]};
describe('document related-record choices',()=>{
 it('labels both order parties, preserving opaque IDs only as values',()=>{const buyer=documentOrderOptions([order],'buyer','мЕД снаб');expect(buyer.items[0]).toMatchObject({id:'opaque-id',label:'Заказ DM-001'});expect(buyer.items[0]?.description).toContain('Мед Снаб');expect(JSON.stringify(buyer.items[0]?.description)).not.toContain('opaque-id');expect(documentOrderOptions([order],'supplier','клиника').items).toHaveLength(1);});
 it('searches numbers and does not show foreign orders',()=>{expect(documentOrderOptions([order],'buyer','dm-001').items).toHaveLength(1);expect(documentOrderOptions([order],'foreign','').items).toEqual([]);expect(documentOrderOptions([order],'buyer','missing').items).toEqual([]);});
 it('bounds rendered results and gives honest truncation',()=>{expect(documentOrderOptions(Array.from({length:101},(_,i)=>({...order,id:String(i)})),'buyer','')).toMatchObject({hasMore:true});expect(documentOrderOptions(Array(101).fill(order),'buyer','').items).toHaveLength(100);});
 it('allows draft and historical contracts as document references, not publication approval',()=>{const result=documentAgreementOptions([contract,{...contract,id:'expired',status:'EXPIRED'},{...contract,id:'invoice',category:'ORDER'}],'buyer',true);expect(result.items.map(x=>x.id)).toEqual(['opaque-contract','expired']);expect(result.items[0]?.label).toBe('ДГ-12 · Договор поставки · версия 2');expect(result.items[0]?.description).toContain('Черновик');expect(result.hasMore).toBe(true);});
 it('deduplicates counterparties and never invents a name from UUID',()=>{expect(documentAgreementOptions([{...contract,participants:[]}],'buyer',false).items[0]?.description).toContain('Контрагент не указан');expect(documentAgreementOptions([{...contract,participants:[...contract.participants,...contract.participants]}],'buyer',false).items[0]?.description.match(/Мед Снаб/g)).toHaveLength(1);});
 it('invalidates late responses after a new request or unmount',()=>{const sequence=createRelationRequestSequence(),old=sequence.next(),fresh=sequence.next();expect(sequence.current(old)).toBe(false);expect(sequence.current(fresh)).toBe(true);sequence.cancel();expect(sequence.current(fresh)).toBe(false);});
 it('distinguishes permission/session/network without exposing backend details',()=>{expect(documentRelationError({status:403})).toContain('Нет доступа');expect(documentRelationError({status:401})).toContain('Сессия');expect(documentRelationError(Error('SQL secret'))).not.toContain('SQL');expect(documentRelationError(Error())).toContain('сохранена');});
});
