import Image from "next/image";

const clinicBenefits = ["Сравнивайте цену за единицу", "Проверяйте наличие и сроки", "Следите за бюджетом", "Получайте документы по заказу"];
const supplierBenefits = ["Управляйте товарами, ценами и остатками", "Загружайте прайс файлом или из 1С", "Запускайте акции и следите за продажами", "Начните продажи после проверки и договора"];
const buyerAppUrl = process.env.NEXT_PUBLIC_BUYER_APP_URL ?? "https://dentmarket-store.vercel.app";
const supplierAppUrl = process.env.NEXT_PUBLIC_SUPPLIER_APP_URL ?? "https://dentmarket-supplier.vercel.app";

export default function LandingPage() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "DentMarket KZ", applicationCategory: "BusinessApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "KZT", description: "Пилотный доступ" }, areaServed: { "@type": "Country", name: "Kazakhstan" } };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="topbar"><a className="brand" href="#top" aria-label="DentMarket KZ, на главную"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><nav aria-label="Навигация"><a href="#clinics">Клиникам</a><a href="#suppliers">Поставщикам</a><a href="#process">Как работает</a><a href="#faq">Вопросы</a></nav><div className="headerActions"><a className="shopLink" href={buyerAppUrl} data-event="header-shop">В магазин</a><a className="login" href="/login" data-event="header-login">Войти</a></div></header>
    <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow">Закупки для стоматологии</p><h1>Материалы, цены и сроки поставки в одном месте</h1><p className="lead">Сравнивайте предложения поставщиков Казахстана и оформляйте заказы с документами.</p><div className="heroActions"><a className="primary" href={buyerAppUrl} data-event="hero-shop">Перейти в магазин</a><a className="secondary" href="/register?role=buyer" data-event="hero-clinic">Зарегистрировать клинику</a><a className="textAction" href={supplierAppUrl} data-event="hero-supplier-cabinet">Кабинет поставщика →</a></div><div className="trust"><span><b>5</b> поставщиков</span><span><b>ЭЦП</b> договор и документы</span><span><b>KZT</b> цены в тенге</span></div></div><div className="heroVisual"><Image src="/dental-procurement-hero.png" alt="Стоматологические материалы и инструменты для закупки" fill priority sizes="(max-width: 900px) 100vw, 52vw" /></div></section>
    <section className="proof" aria-label="Ключевые возможности"><p>Каталог без дублей</p><p>Цена за штуку и упаковку</p><p>Актуальные остатки</p><p>Заказы нескольким поставщикам</p><p>Проверка документов</p></section>
    <section className="audience" id="clinics"><div className="sectionIntro"><p className="eyebrow">Для клиник</p><h2>Закупка без цепочки звонков</h2><p>Сравнивайте предложения, контролируйте бюджет и повторяйте регулярные заказы.</p></div><div className="featureGrid">{clinicBenefits.map((item, index) => <article key={item}><h3>{item}</h3><p>{["Сразу видно цену за штуку и упаковку.", "Рядом с ценой указаны количество и доставка.", "Лимиты помогают не выйти за план.", "Счёт и остальные документы хранятся в заказе."][index]}</p></article>)}</div><div className="sectionActions"><a className="primary" href={buyerAppUrl} data-event="clinic-shop">Открыть магазин</a><a className="secondary" href="/register?role=buyer">Создать аккаунт клиники</a></div></section>
    <section className="supplierSection" id="suppliers"><div className="supplierPanel"><div><p className="eyebrow">Для поставщиков</p><h2>Все заказы в одном кабинете</h2><p>Загружайте товары, подтверждайте заказы и следите за продажами и выплатами.</p><div className="supplierActions"><a className="lightButton" href={supplierAppUrl} data-event="supplier-cabinet">Открыть кабинет</a><a className="lightText" href="/register?role=supplier" data-event="supplier-cta">Стать поставщиком →</a></div></div><ol>{supplierBenefits.map((item) => <li key={item}>{item}</li>)}</ol></div></section>
    <section className="process" id="process"><div className="sectionIntro"><p className="eyebrow">От поиска до поставки</p><h2>Четыре понятных шага</h2></div><div className="steps"><article><h3>Найдите</h3><p>Ищите по названию, бренду, характеристикам или категории.</p></article><article><h3>Сравните</h3><p>Проверьте цену, упаковку, наличие и доставку.</p></article><article><h3>Оформите</h3><p>Мы разделим корзину на заказы разным поставщикам.</p></article><article><h3>Получите</h3><p>Следите за оплатой, доставкой, возвратами и документами.</p></article></div></section>
    <section className="legal"><div><p className="eyebrow">Договор с поставщиком</p><h2>Подпишите один раз в год</h2></div><p>Подпишите договор с DentMarket через ЭЦП. Повторная подпись понадобится после окончания срока или изменения условий.</p></section>
    <section className="faq" id="faq"><div className="sectionIntro"><p className="eyebrow">Вопросы</p><h2>Коротко о работе сервиса</h2></div><div>{[["Кто может покупать?","Клиники и другие организации стоматологического профиля после регистрации."],["Как проверяются поставщики?","До начала продаж мы проверяем реквизиты и обязательные документы поставщика."],["Можно ли подключить учётную систему?","Да. Можно загрузить прайс файлом или подключить 1С и другую учётную систему."],["Как работает договор с ЭЦП?","Поставщик и DentMarket подписывают договор через ЭЦП. После подписания можно начинать продажи."],["Сколько стоит подключение?","Сейчас плата не списывается. О новых условиях сообщим заранее."]].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="finalCta"><p className="eyebrow">Начните сейчас</p><h2>Управляйте закупками и продажами в DentMarket</h2><div><a className="primary" href={buyerAppUrl} data-event="final-shop">В магазин</a><a className="secondary" href="/register?role=buyer" data-event="final-clinic">Зарегистрировать клинику</a><a className="secondary" href={supplierAppUrl} data-event="final-supplier">Кабинет поставщика</a></div></section>
    <footer><a className="brand" href="#top"><span>DM</span><strong>DentMarket <small>KZ</small></strong></a><p>Закупки для стоматологий Казахстана. <a href="/legal/terms">Условия</a> <a href="/legal/privacy">Конфиденциальность</a></p><p>© 2026 DentMarket KZ</p></footer>
  </main>;
}
