export const WEBHOOK_MAX_BODY_BYTES = 1_048_576;
export const WEBHOOK_RATE_LIMIT = 120;
export const WEBHOOK_RATE_TTL_MS = 60_000;
export const INTEGRATION_WEBHOOK_MAX_BODY_BYTES = WEBHOOK_MAX_BODY_BYTES;
export const INTEGRATION_WEBHOOK_RATE_LIMIT = WEBHOOK_RATE_LIMIT;
export const INTEGRATION_WEBHOOK_RATE_TTL_MS = WEBHOOK_RATE_TTL_MS;
